services:
  angular:
    build:
      context: .
      dockerfile: docker/angular.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start -- --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    networks:
      - mes

networks:
  mes:
